const mcqQuestions = [
    
    {
        question: "According to FISMA, what must federal information systems do regardless of their impact categorization?",
        options: ["Conduct monthly vulnerability scans", "Scan for vulnerabilities and report new ones", "Hire external security consultants", "Implement biometric authentication"],
        answer: 1,
        explanation: "FISMA (Federal Information Security Modernization Act) requires federal information systems to continuously scan for vulnerabilities and report any newly discovered ones, regardless of their impact level, to ensure ongoing security monitoring."
    },
    {
        question: "What does CVSS stand for?",
        options: ["Common Vulnerability Scoring System", "Cyber Vulnerability Security Standard", "Central Virus Scanning Service", "Critical Vulnerability Security System"],
        answer: 0,
        explanation: "CVSS stands for Common Vulnerability Scoring System, a standardized method for assessing the severity of security vulnerabilities in software and systems.",
    },
    {
        question: "What is the highest possible CVSS base score?",
        options: ["5", "8", "10", "100"],
        answer: 2,
        explanation: "The CVSS base score ranges from 0 to 10, with 10 being the highest possible score, indicating the most severe vulnerabilities.",
    },
    {
        question: "What does NAT stand for in networking?",
        options: ["Network Access Technology", "Network Address Translation", "National Authorization Token", "Network Automation Tool"],
        answer: 1,
        explanation: "NAT stands for Network Address Translation, a technique used in networking to modify network address information in IP packet headers while in transit across a traffic routing device.",
    },
    {
        question: "Which CVSS score range is classified as High risk?",
        options: ["0.1-3.9", "4.0-6.9", "7.0-8.9", "9.0-10.0"],
        answer: 2,
        explanation: "In CVSS, scores from 7.0 to 8.9 are classified as High risk, indicating vulnerabilities that are significant but not the most critical.",
    },
    {
        question: "What does a false positive in vulnerability scanning mean?",
        options: ["A vulnerability that exists but wasn't detected", "A vulnerability reported that doesn't actually exist", "A correctly identified vulnerability", "A negative scan result"],
        answer: 1,
        explanation: "A false positive occurs when a vulnerability scanner incorrectly reports a vulnerability that does not actually exist, leading to unnecessary concern or remediation efforts.",
    },
    {
        question: "What is the Dirty COW attack an example of?",
        options: ["Malicious code", "Privilege escalation", "Buffer overflow", "LDAP injection"],
        answer: 1,
        explanation: "Dirty COW (Dirty Copy-on-Write) is a privilege escalation vulnerability in the Linux kernel that allows an attacker to gain higher privileges by exploiting a race condition in memory management.",
    },
    {
        question: "Which protocol should replace Telnet for secure remote access?",
        options: ["FTP", "HTTP", "SSH", "SMTP"],
        answer: 2,
        explanation: "SSH (Secure Shell) is the secure replacement for Telnet, providing encrypted communication for remote access to systems.",
    },
    {
        question: "What does SQL injection exploit?",
        options: ["Operating system vulnerabilities", "Web application vulnerabilities", "Network protocol weaknesses", "Hardware flaws"],
        answer: 1,
        explanation: "SQL injection exploits vulnerabilities in web applications by injecting malicious SQL code into queries, potentially allowing unauthorized access to databases.",
    },
    {
        question: "What is XSS short for?",
        options: ["Extra Security System", "Cross-Site Scripting", "eXternal System Security", "eXtended SQL Statement"],
        answer: 1,
        explanation: "XSS stands for Cross-Site Scripting, a type of security vulnerability in web applications that allows attackers to inject malicious scripts into web pages viewed by other users.",
    },
    {
        question: "What is a hypervisor used for?",
        options: ["Managing passwords", "Mediating access to hardware in virtualization", "Scanning for viruses", "Encrypting data"],
        answer: 1,
        explanation: "A hypervisor is software that mediates access to hardware resources in virtualization, allowing multiple virtual machines to run on a single physical host.",
    },
    {
        question: "What does IoT stand for?",
        options: ["Internet of Things", "Internal Operations Technology", "Integrated Online Tools", "International Operating Terms"],
        answer: 0,
        explanation: "IoT stands for Internet of Things, referring to the network of physical devices connected to the internet that can collect and exchange data.",
    },
    {
        question: "What is SCADA used for?",
        options: ["Email security", "Industrial control systems", "Password management", "Web browsing"],
        answer: 1,
        explanation: "SCADA (Supervisory Control and Data Acquisition) is used for monitoring and controlling industrial processes, such as in manufacturing or utilities.",
    },
    {
        question: "What does PLC stand for in IoT?",
        options: ["Programmable Logic Controller", "Private Local Connection", "Public License Code", "Protected Link Communication"],
        answer: 0,
        explanation: "PLC stands for Programmable Logic Controller, a type of computer used in IoT and industrial automation to control machinery and processes.",
    },
    {
        question: "What is a man-in-the-middle attack?",
        options: ["Intercepting communication between two systems", "Physical theft of data", "Denial of service", "Virus infection"],
        answer: 0,
        explanation: "A man-in-the-middle attack involves an attacker intercepting and possibly altering communication between two parties without their knowledge.",
    },
    {
        question: "What does password spraying target?",
        options: ["Multiple passwords on one account", "Common passwords across many accounts", "Encrypted passwords", "Biometric authentication"],
        answer: 1,
        explanation: "Password spraying is an attack where common passwords are tried across many user accounts to gain unauthorized access, rather than brute-forcing one account.",
    },
    {
        question: "What is credential stuffing?",
        options: ["Creating strong passwords", "Using stolen credentials from one site on another", "Encrypting passwords", "Multi-factor authentication"],
        answer: 1,
        explanation: "Credential stuffing involves using lists of stolen usernames and passwords from one breach to attempt logins on other websites.",
    },
    {
        question: "According to PCI DSS, how often must organizations run vulnerability scans?",
        options: ["Daily", "Weekly", "Monthly", "Quarterly"],
        answer: 3,
        explanation: "PCI DSS (Payment Card Industry Data Security Standard) requires organizations to perform vulnerability scans at least quarterly to maintain compliance.",
    },
    {
        question: "What is Nessus?",
        options: ["An antivirus program", "A vulnerability scanner", "A firewall", "An operating system"],
        answer: 1,
        explanation: "Nessus is a widely used vulnerability scanner that identifies security weaknesses in networks, systems, and applications.",
    },
    {
        question: "What does an ASV do in PCI DSS compliance?",
        options: ["Develops applications", "Conducts external vulnerability scans", "Manages passwords", "Trains employees"],
        answer: 1,
        explanation: "An ASV (Approved Scanning Vendor) is authorized by PCI DSS to perform external vulnerability scans on merchant systems.",
    },
    {
        question: "What is the purpose of credentialed scanning?",
        options: ["To hack systems", "To retrieve configuration information from target servers", "To block network traffic", "To encrypt data"],
        answer: 1,
        explanation: "Credentialed scanning uses valid credentials to access systems and identify internal vulnerabilities and misconfigurations.",
    },
    {
        question: "What does OpenVAS stand for?",
        options: ["Open Virtual Awareness System", "Open Vulnerability Assessment System", "Open Virus Antivirus Scanner", "Open VPN Access Server"],
        answer: 1,
        explanation: "OpenVAS (Open Vulnerability Assessment System) is a free and open-source vulnerability scanner.",
    },
    {
        question: "What is a false negative in vulnerability scanning?",
        options: ["A vulnerability that doesn't exist", "An actual vulnerability not detected by the scanner", "A correctly identified vulnerability", "A positive scan result"],
        answer: 1,
        explanation: "A false negative occurs when a vulnerability scanner fails to detect a vulnerability that actually exists.",
    },
    {
        question: "What does OWASP stand for?",
        options: ["Open Web Application Security Project", "Organized Web Access Security Plan", "Online Web Application Standards Protocol", "Operational Web Audit Security Program"],
        answer: 0,
        explanation: "OWASP (Open Web Application Security Project) is a nonprofit organization focused on improving software security.",
    },
    {
        question: "What is the OWASP Top 10?",
        options: ["Ten networking protocols", "Ten most critical web application security risks", "Ten password rules", "Ten firewalls"],
        answer: 1,
        explanation: "The OWASP Top 10 is a list of the ten most critical web application security vulnerabilities and risks.",
    },
    {
        question: "What does TLS stand for?",
        options: ["Transport Layer Security", "Technical Layer Service", "Trusted Link Service", "Transmission Line Signal"],
        answer: 0,
        explanation: "TLS (Transport Layer Security) is a cryptographic protocol for secure communication over networks.",
    },
    {
        question: "What is the difference between SSL and TLS?",
        options: ["They are the same", "TLS is the newer, more secure version of SSL", "SSL is newer", "They serve different purposes"],
        answer: 1,
        explanation: "TLS is the successor to SSL (Secure Sockets Layer) and provides improved security.",
    },
    {
        question: "What does a digital certificate contain?",
        options: ["Only the public key", "Public key, identity information, and digital signature", "Only the private key", "Just encryption algorithms"],
        answer: 1,
        explanation: "A digital certificate contains the public key, identity information, and is signed by a Certificate Authority.",
    },
    {
        question: "What does CA stand for in digital certificates?",
        options: ["Central Authority", "Certificate Authority", "Cyber Authentication", "Code Analyzer"],
        answer: 1,
        explanation: "CA stands for Certificate Authority, an entity that issues digital certificates to verify the identity of websites and encrypt communications.",
    },
    {
        question: "What is SET protocol designed for?",
        options: ["Email encryption", "Secure electronic transactions", "File transfer", "Network monitoring"],
        answer: 1,
        explanation: "SET (Secure Electronic Transaction) is a protocol designed to secure credit card transactions over the internet.",
    },
    {
        question: "Which organizations initially adopted SET protocol in 1996?",
        options: ["PayPal and eBay", "MasterCard and VISA", "Amazon and Google", "Microsoft and Apple"],
        answer: 1,
        explanation: "MasterCard and VISA initially adopted the SET protocol in 1996 to provide secure online payment processing.",
    },
    {
        question: "What does CNP stand for in fraud detection?",
        options: ["Central Network Protocol", "Card Not Present", "Customer Name Protection", "Cyber Network Prevention"],
        answer: 1,
        explanation: "CNP stands for Card Not Present, referring to online transactions where the physical card is not used, increasing fraud risks.",
    },
    {
        question: "What is WEP in wireless security?",
        options: ["Wireless Encryption Protocol", "Wired Equivalent Privacy", "Web Encryption Privacy", "Wireless Enhanced Protection"],
        answer: 1,
        explanation: "WEP stands for Wired Equivalent Privacy, an early encryption standard for wireless networks, now considered insecure.",
    },
    {
        question: "Which wireless encryption is the strongest?",
        options: ["WEP", "WPA", "WPA2", "WPA3"],
        answer: 3,
        explanation: "WPA3 is the strongest wireless encryption standard, offering improved security features over WPA2.",
    },
    {
        question: "What does SSID stand for?",
        options: ["System Security Identifier", "Service Set Identifier", "Secure Socket Interface Device", "Standard Security ID"],
        answer: 1,
        explanation: "SSID stands for Service Set Identifier, the name of a wireless network that devices use to connect.",
    },
    {
        question: "What is a rogue access point?",
        options: ["A broken router", "An unauthorized wireless device on the network", "A secure access point", "A backup router"],
        answer: 1,
        explanation: "A rogue access point is an unauthorized wireless access point connected to a network, potentially allowing attackers to intercept traffic.",
    },
    {
        question: "What does KRACK vulnerability target?",
        options: ["WEP", "Bluetooth", "WPA/WPA2", "Ethernet"],
        answer: 2,
        explanation: "KRACK (Key Reinstallation Attack) exploits vulnerabilities in WPA/WPA2 protocols, allowing decryption of wireless traffic.",
    },
    {
        question: "What is the IEEE 802.11 protocol stack used for?",
        options: ["Wired networks", "Wireless networks", "Bluetooth", "Cellular networks"],
        answer: 1,
        explanation: "IEEE 802.11 is the standard for wireless local area networks (WLANs).",
    },
    {
        question: "What percentage of IoT devices had security vulnerabilities according to HP research?",
        options: ["30 percent", "50 percent", "70 percent", "90 percent"],
        answer: 2,
        explanation: "HP research found that 70 percent of IoT devices had security vulnerabilities.",
    },
    {
        question: "What is Android OS based on?",
        options: ["Windows kernel", "Modified Linux kernel", "Unix kernel", "BSD kernel"],
        answer: 1,
        explanation: "Android is based on a modified version of the Linux kernel.",
    },
    {
        question: "What is the global market share of Android OS?",
        options: ["45.5 percent", "60.2 percent", "74.45 percent", "85.3 percent"],
        answer: 2,
        explanation: "Android holds approximately 74.45 percent of the global mobile OS market share.",
    },
    {
        question: "What does MDM stand for in mobile security?",
        options: ["Mobile Data Manager", "Mobile Device Management", "Multi-Device Monitor", "Master Data Module"],
        answer: 1,
        explanation: "MDM stands for Mobile Device Management, used to secure and manage mobile devices in organizations.",
    },
    {
        question: "What is MAM in mobile security?",
        options: ["Mobile Access Manager", "Multi-Authentication Method", "Mobile Application Management", "Master Access Module"],
        answer: 2,
        explanation: "MAM stands for Mobile Application Management, focusing on securing and managing apps on mobile devices.",
    },
    {
        question: "What does BYOD stand for?",
        options: ["Bring Your Own Device", "Build Your Own Database", "Backup Your Own Data", "Browse Your Online Documents"],
        answer: 0,
        explanation: "BYOD stands for Bring Your Own Device, referring to employees using personal devices for work.",
    },
    {
        question: "According to McAfee report Q1 2018, what percentage increase in ad clicks was noticed?",
        options: ["12 percent", "22 percent", "36 percent", "45 percent"],
        answer: 2,
        explanation: "McAfee reported a 36 percent increase in ad clicks in Q1 2018, indicating rising mobile ad risks.",
    },
    {
        question: "What is the recommended encryption level for password managers?",
        options: ["128-bit", "192-bit", "256-bit or higher", "512-bit"],
        answer: 2,
        explanation: "Password managers should use at least 256-bit encryption for strong security.",
    },
    {
        question: "What is a keylogger?",
        options: ["Password manager", "Spyware that records keystrokes", "Encryption tool", "Firewall software"],
        answer: 1,
        explanation: "A keylogger is spyware that captures keystrokes to steal sensitive information like passwords.",
    },
    {
        question: "What does the S in HTTPS represent?",
        options: ["System", "Secure", "Standard", "Simple"],
        answer: 1,
        explanation: "The S in HTTPS stands for Secure, indicating encrypted communication.",
    },
    
    {
        question: "What is computational thinking?",
        options: ["Programming in a computer", "Solving problems using computer science concepts", "Using a computer to think", "Thinking about computers"],
        answer: 1,
        explanation: "Computational thinking is a problem-solving approach using concepts like abstraction, algorithms, and decomposition.",
    },
    {
        question: "Which of the following is NOT a key aspect of computational thinking?",
        options: ["Decomposition", "Pattern recognition", "Abstraction", "Physical computing"],
        answer: 3,
        explanation: "Decomposition, pattern recognition, and abstraction are core aspects. Physical computing is a different field.",
    },
    {
        question: "What does abstraction help us do?",
        options: ["Make programs faster", "Hide complexity and focus on relevant details", "Use less memory", "Write less code"],
        answer: 1,
        explanation: "Abstraction allows us to hide implementation details and focus on what matters for solving a problem.",
    },
    {
        question: "What is an algorithm?",
        options: ["A programming language", "A step-by-step procedure to solve a problem", "A data structure", "A type of variable"],
        answer: 1,
        explanation: "An algorithm is a finite set of instructions to accomplish a task or solve a problem.",
    },
    {
        question: "What is Big O notation used for?",
        options: ["Measuring code quality", "Analyzing time and space complexity of algorithms", "Creating algorithms", "Debugging code"],
        answer: 1,
        explanation: "Big O notation describes how an algorithm's performance scales with input size.",
    },
    {
        question: "Which Big O complexity is the most efficient?",
        options: ["O(n squared)", "O(n)", "O(1)", "O(log n)"],
        answer: 2,
        explanation: "O(1) constant time is the most efficient as it does not depend on input size.",
    },
    {
        question: "What does O(n) complexity mean?",
        options: ["Constant time", "Linear time", "Quadratic time", "Logarithmic time"],
        answer: 1,
        explanation: "O(n) means the algorithm's time scales linearly with the input size n.",
    },
    {
        question: "What is a data structure?",
        options: ["A programming language", "A way to organize and store data", "A type of function", "An algorithm"],
        answer: 1,
        explanation: "A data structure is a specialized format for organizing, managing, and storing data efficiently.",
    },
    {
        question: "Which is NOT a common data structure?",
        options: ["Array", "LinkedList", "HashMap", "Probability"],
        answer: 3,
        explanation: "Probability is a mathematical concept, not a data structure. Arrays, LinkedLists, and HashMaps are all data structures.",
    },
    {
        question: "What is time complexity?",
        options: ["How much time a computer takes to run", "How an algorithm's running time grows with input size", "The duration of a program", "Clock speed"],
        answer: 1,
        explanation: "Time complexity analyzes how the number of operations grows as the input size increases.",
    },
    {
        question: "How many bits are in a byte?",
        options: ["4", "8", "16", "32"],
        answer: 1,
        explanation: "A byte consists of 8 bits, the fundamental unit of computer memory.",
    },
    {
        question: "What does binary use to represent data?",
        options: ["0-9", "A-Z", "0 and 1", "True and False"],
        answer: 2,
        explanation: "Binary is a base-2 number system using only 0 and 1 to represent all data in computers.",
    },
    {
        question: "What is the decimal equivalent of binary 1010?",
        options: ["8", "10", "12", "15"],
        answer: 1,
        explanation: "1010 in binary equals 1 times 8 plus 0 times 4 plus 1 times 2 plus 0 times 1, which equals 8 plus 2 equals 10 in decimal.",
    },
    {
        question: "What does ASCII stand for?",
        options: ["American Standard Code for Information Interchange", "Advanced System for Computing Information", "Algorithmic System Code Interface", "American Software Computing Interface"],
        answer: 0,
        explanation: "ASCII is a character encoding standard that maps numbers to text characters.",
    },
    {
        question: "How many unique values can 8 bits represent?",
        options: ["128", "256", "512", "1024"],
        answer: 1,
        explanation: "8 bits can represent 2 to the power of 8, which equals 256 different values from 0 to 255.",
    },
    {
        question: "What is the hexadecimal equivalent of decimal 255?",
        options: ["FF", "FE", "100", "AF"],
        answer: 0,
        explanation: "255 in decimal equals FF in hexadecimal, which is 15 times 16 plus 15 equals 255.",
    },
    {
        question: "What does Unicode support that ASCII does not?",
        options: ["Numbers", "Special characters", "Characters from all world languages", "Punctuation"],
        answer: 2,
        explanation: "Unicode supports characters from virtually all languages worldwide, while ASCII is limited to English.",
    },
    {
        question: "How many bits does a typical color require in RGB?",
        options: ["8", "16", "24", "32"],
        answer: 2,
        explanation: "RGB colors typically use 24 bits: 8 bits each for Red, Green, and Blue.",
    },
    {
        question: "What is a pixel?",
        options: ["A small picture", "The smallest unit of a digital image", "A type of monitor", "A color value"],
        answer: 1,
        explanation: "A pixel is the smallest unit of a digital image, typically represented as a single color.",
    },
    {
        question: "What is lossless compression?",
        options: ["Compression that removes some data", "Compression where original data can be perfectly reconstructed", "Compression that reduces file size significantly", "Compression that loses quality"],
        answer: 1,
        explanation: "Lossless compression allows perfect reconstruction of original data with no loss of information.",
    },
    {
        question: "What is lossy compression?",
        options: ["Compression that removes some data permanently", "Compression that removes all unnecessary files", "Compression that is incomplete", "Compression that fails"],
        answer: 0,
        explanation: "Lossy compression removes some data to reduce file size but cannot perfectly reconstruct the original.",
    },
    {
        question: "Which image format uses lossy compression?",
        options: ["PNG", "JPEG", "GIF", "BMP"],
        answer: 1,
        explanation: "JPEG uses lossy compression to achieve smaller file sizes while maintaining reasonable quality.",
    },
    {
        question: "What is the purpose of a checksum?",
        options: ["Compress files", "Verify data integrity", "Encrypt data", "Organize files"],
        answer: 1,
        explanation: "A checksum is used to verify that data has not been corrupted or altered.",
    },
    {
        question: "What is the parity bit used for?",
        options: ["Increasing data size", "Detecting single-bit errors", "Encrypting data", "Compressing files"],
        answer: 1,
        explanation: "A parity bit helps detect single-bit errors in data transmission.",
    },
    {
        question: "How does Hamming code improve upon parity bits?",
        options: ["It cannot", "It can only detect errors", "It can detect and correct single-bit errors", "It is just another name for parity"],
        answer: 2,
        explanation: "Hamming code can both detect and correct single-bit errors, making it more robust than simple parity bits.",
    },
    {
        question: "What is linear search?",
        options: ["Searching in a straight line", "Checking each element sequentially until found", "Drawing lines on paper to search", "A fast search method"],
        answer: 1,
        explanation: "Linear search checks each element one by one, with O(n) time complexity.",
    },
    {
        question: "What is the time complexity of linear search?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n squared)"],
        answer: 2,
        explanation: "Linear search has O(n) time complexity as it may need to check every element.",
    },
    {
        question: "What is binary search?",
        options: ["Searching for binary files", "Using division to search in sorted data", "Searching for zeros and ones", "A type of linear search"],
        answer: 1,
        explanation: "Binary search repeatedly divides a sorted list in half, achieving O(log n) complexity.",
    },
    {
        question: "What is a requirement for binary search?",
        options: ["Data must be in a linked list", "Data must be sorted", "Data must be in a specific format", "Data must be of equal size"],
        answer: 1,
        explanation: "Binary search requires the data to be sorted to work correctly.",
    },
    {
        question: "What is the time complexity of binary search?",
        options: ["O(n)", "O(n squared)", "O(log n)", "O(1)"],
        answer: 2,
        explanation: "Binary search has O(log n) complexity by eliminating half the data each iteration.",
    },
    {
        question: "What is a hash function?",
        options: ["A function that hashes code", "A function that converts input to a fixed-size output", "A function that searches data", "A function that stores data"],
        answer: 1,
        explanation: "A hash function takes input and produces a fixed-size hash value for efficient lookup.",
    },
    {
        question: "What is a hash table?",
        options: ["A table made of hashing", "A data structure that uses hash functions for fast lookup", "A table of hash values", "A method of sorting"],
        answer: 1,
        explanation: "A hash table uses hash functions to map keys to indices for O(1) average lookup time.",
    },
    {
        question: "What is a hash collision?",
        options: ["When hashing crashes", "When two different inputs produce the same hash value", "When hash function fails", "When memory is full"],
        answer: 1,
        explanation: "A hash collision occurs when different inputs hash to the same value, requiring resolution.",
    },
    {
        question: "What is bubble sort?",
        options: ["Sorting by creating bubbles", "A sorting algorithm that repeatedly swaps adjacent elements", "Sorting in alphabetical order", "A fast sorting method"],
        answer: 1,
        explanation: "Bubble sort compares adjacent elements and swaps them if they are in the wrong order.",
    },
    {
        question: "What is the time complexity of bubble sort?",
        options: ["O(n)", "O(n log n)", "O(n squared)", "O(log n)"],
        answer: 2,
        explanation: "Bubble sort has O(n squared) time complexity in the worst and average cases.",
    },
    {
        question: "What is selection sort?",
        options: ["Selecting and sorting", "Finding minimum element and swapping to correct position repeatedly", "Selecting specific elements", "A comparison-based sort"],
        answer: 1,
        explanation: "Selection sort repeatedly finds the minimum element and places it in the correct position.",
    },
    {
        question: "What is the time complexity of selection sort?",
        options: ["O(n)", "O(n log n)", "O(n squared)", "O(log n)"],
        answer: 2,
        explanation: "Selection sort has O(n squared) complexity regardless of input order.",
    },
    {
        question: "What is insertion sort?",
        options: ["Inserting elements in random positions", "Building sorted array by inserting elements one by one", "Inserting in the middle", "A type of linear search"],
        answer: 1,
        explanation: "Insertion sort builds the sorted array by inserting each element into its correct position.",
    },
    {
        question: "What is merge sort?",
        options: ["Merging two sorted lists", "A divide-and-conquer sorting algorithm", "Sorting by merging files", "A comparison sort"],
        answer: 1,
        explanation: "Merge sort divides data in half, recursively sorts, then merges sorted halves.",
    },
    {
        question: "What is the time complexity of merge sort?",
        options: ["O(n)", "O(n log n)", "O(n squared)", "O(log n)"],
        answer: 1,
        explanation: "Merge sort has O(n log n) complexity in all cases due to its divide-and-conquer approach.",
    },
    {
        question: "What is quick sort?",
        options: ["A fast sort", "A sorting algorithm that uses a pivot to partition data", "Sorting quickly", "The fastest sort"],
        answer: 1,
        explanation: "Quick sort selects a pivot and partitions data, then recursively sorts partitions.",
    },
    {
        question: "What is the worst-case complexity of quick sort?",
        options: ["O(n)", "O(n log n)", "O(n squared)", "O(1)"],
        answer: 2,
        explanation: "Quick sort's worst case is O(n squared) when pivot selection is poor.",
    },
    {
        question: "What is a linear data structure?",
        options: ["A structure with lines", "Elements arranged in sequence", "A 2D structure", "A database structure"],
        answer: 1,
        explanation: "Linear data structures arrange elements in sequence (arrays, lists, stacks, queues).",
    },
    {
        question: "What is an array?",
        options: ["A collection of related data in sequence", "A single value", "A type of function", "A variable"],
        answer: 0,
        explanation: "An array is a collection of elements stored in contiguous memory locations.",
    },
    {
        question: "What is the time complexity of accessing an element in an array by index?",
        options: ["O(n)", "O(n squared)", "O(log n)", "O(1)"],
        answer: 3,
        explanation: "Array access by index is O(1) constant time since elements are stored contiguously.",
    },
    {
        question: "What is a linked list?",
        options: ["A list of linked websites", "A data structure where elements point to the next element", "A list with links", "An array with pointers"],
        answer: 1,
        explanation: "A linked list is a linear data structure where each node contains data and a reference to the next node.",
    },
    {
        question: "What is the time complexity of searching in a linked list?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n squared)"],
        answer: 2,
        explanation: "Linked list search is O(n) because you must traverse from the start.",
    },
    {
        question: "What is a stack?",
        options: ["A pile of items", "LIFO data structure meaning Last In First Out", "A queue data structure", "An array"],
        answer: 1,
        explanation: "A stack is LIFO, meaning the last element added is the first one removed.",
    },
    {
        question: "What is a queue?",
        options: ["A line of people", "FIFO data structure meaning First In First Out", "A stack data structure", "A linked list"],
        answer: 1,
        explanation: "A queue is FIFO, meaning the first element added is the first one removed.",
    },
    {
        question: "What is the primary use of a stack?",
        options: ["Efficient searching", "Function call management and undo operations", "Sorting data", "Finding minimum and maximum"],
        answer: 1,
        explanation: "Stacks are used in function calls (call stack), undo/redo, and expression evaluation.",
    },
    {
        question: "What is the primary use of a queue?",
        options: ["Sorting data", "Task scheduling and breadth-first search", "Finding paths", "Storing temporary data"],
        answer: 1,
        explanation: "Queues are used for task scheduling, BFS, and maintaining order.",
    },
    {
        question: "What is a tree?",
        options: ["A plant structure", "A hierarchical data structure with nodes and edges", "A binary search structure", "A graph structure"],
        answer: 1,
        explanation: "A tree is a hierarchical data structure with a root node and parent-child relationships.",
    },
    {
        question: "What is a binary tree?",
        options: ["A tree with 2 nodes", "A tree where each node has at most 2 children", "A tree with 2 levels", "A tree with binary data"],
        answer: 1,
        explanation: "A binary tree has nodes with at most 2 children (left and right).",
    },
    {
        question: "What is a binary search tree (BST)?",
        options: ["A tree that performs binary search", "A binary tree with ordered values", "A tree for quick sorting", "An unordered tree"],
        answer: 1,
        explanation: "A BST is a binary tree where left subtree values are less than parent, which is less than right subtree values.",
    },
    {
        question: "What is the time complexity of searching in a balanced BST?",
        options: ["O(n)", "O(n squared)", "O(log n)", "O(1)"],
        answer: 2,
        explanation: "A balanced BST has O(log n) search complexity due to logarithmic division.",
    },
    {
        question: "What is a balanced tree?",
        options: ["A tree that does not fall over", "A tree where height difference of subtrees is minimal", "A tree with equal nodes", "A complete tree"],
        answer: 1,
        explanation: "A balanced tree minimizes height difference between subtrees for optimal performance.",
    },
    {
        question: "What is the purpose of tree rotation in AVL trees?",
        options: ["To organize data", "To maintain balance and O(log n) complexity", "To sort data", "To store more data"],
        answer: 1,
        explanation: "Rotations in AVL trees maintain balance to ensure O(log n) operations.",
    },
    {
        question: "What is depth-first search (DFS)?",
        options: ["Searching with maximum depth", "Traversing graph by going deep before exploring siblings", "Searching at depth level", "A linear search"],
        answer: 1,
        explanation: "DFS uses a stack and explores as far as possible along each branch before backtracking.",
    },
    {
        question: "What is breadth-first search (BFS)?",
        options: ["Searching with maximum breadth", "Traversing graph level by level", "Searching at breadth level", "A quick search"],
        answer: 1,
        explanation: "BFS uses a queue and explores all neighbors before moving to the next level.",
    },
    {
        question: "When would you prefer BFS over DFS?",
        options: ["For finding shortest path", "For memory efficiency", "For depth exploration", "For stack-based operations"],
        answer: 0,
        explanation: "BFS finds the shortest path in unweighted graphs, while DFS uses less memory.",
    },
    {
        question: "What is Dijkstra's algorithm used for?",
        options: ["Sorting data", "Finding shortest paths in weighted graphs", "Searching trees", "Organizing data"],
        answer: 1,
        explanation: "Dijkstra's algorithm finds the shortest path from a source to all other nodes in weighted graphs.",
    },
    {
        question: "What does C stand for?",
        options: ["Computer", "Compiler", "It is just called C", "Code"],
        answer: 2,
        explanation: "C is simply called C, developed by Dennis Ritchie in the early 1970s.",
    },
    {
        question: "What is a variable?",
        options: ["Something that changes", "A named storage location for a value", "A mathematical expression", "A function"],
        answer: 1,
        explanation: "A variable is a named container that stores a value.",
    },
    {
        question: "What are the primitive data types in C?",
        options: ["int, char, float, double, void", "string, boolean, number", "object, array, function", "text, number, boolean"],
        answer: 0,
        explanation: "C's primitive types are int, char, float, double, and void.",
    },
    {
        question: "What is the size of an int in C on most systems?",
        options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"],
        answer: 2,
        explanation: "An int is typically 4 bytes (32 bits) on most modern systems.",
    },
    {
        question: "What is the purpose of the printf function?",
        options: ["Print formatting", "Output formatted text to the console", "Create formatted strings", "Print errors"],
        answer: 1,
        explanation: "printf outputs formatted text to the standard output (console).",
    },
    {
        question: "What is the purpose of the scanf function?",
        options: ["Scan files", "Read formatted input from user", "Search for text", "Compile code"],
        answer: 1,
        explanation: "scanf reads formatted input from the user into variables.",
    },
    {
        question: "What does string formatting with percent s in C do?",
        options: ["Prints the address", "Prints a string", "Prints an integer", "Prints a float"],
        answer: 1,
        explanation: "Percent s is used to print a string in printf and scanf.",
    },
    {
        question: "What does percent d represent in format strings?",
        options: ["Double", "Decimal number", "Integer in decimal", "Data"],
        answer: 2,
        explanation: "Percent d is used for printing integers in decimal format.",
    },
    {
        question: "What is a pointer?",
        options: ["A visual indicator", "A variable that stores a memory address", "A type of comment", "A function"],
        answer: 1,
        explanation: "A pointer is a variable that holds the memory address of another variable.",
    },
    {
        question: "What operator gets the address of a variable?",
        options: ["asterisk", "ampersand", "arrow", "arrow asterisk"],
        answer: 1,
        explanation: "The ampersand operator returns the memory address of a variable.",
    },
    {
        question: "What operator dereferences a pointer?",
        options: ["ampersand", "asterisk", "arrow", "period"],
        answer: 1,
        explanation: "The asterisk operator dereferences a pointer to access the value at that address.",
    },
    {
        question: "What is an array in C?",
        options: ["A variable", "A collection of elements of the same type", "A data structure", "A pointer"],
        answer: 1,
        explanation: "An array is a fixed-size collection of elements stored in contiguous memory.",
    },
    {
        question: "How are arrays indexed in C?",
        options: ["Starting from 1", "Starting from 0", "Starting from -1", "No specific order"],
        answer: 1,
        explanation: "C arrays are zero-indexed, starting from 0.",
    },
    {
        question: "What is a string in C?",
        options: ["A type of data", "An array of characters ending with null terminator", "A text variable", "A pointer to characters"],
        answer: 1,
        explanation: "A C string is an array of characters terminated by the null character.",
    },
    {
        question: "What is the null terminator in C strings?",
        options: ["A space character", "The null character marking end of string", "The end of the program", "A special terminator"],
        answer: 1,
        explanation: "The null terminator marks the end of a string and is essential for string functions.",
    },
    {
        question: "What does strcpy do?",
        options: ["Compares strings", "Copies one string to another", "Counts string length", "Concatenates strings"],
        answer: 1,
        explanation: "strcpy copies the contents of one string to another.",
    },
    {
        question: "What does strlen return?",
        options: ["The memory address of a string", "The length of a string", "A copy of the string", "True if valid"],
        answer: 1,
        explanation: "strlen returns the number of characters in a string, excluding the null terminator.",
    },
    {
        question: "What does strcmp do?",
        options: ["Copies strings", "Compares two strings", "Counts characters", "Concatenates strings"],
        answer: 1,
        explanation: "strcmp compares two strings and returns 0 if equal, less than 0 or greater than 0 if different.",
    },
    {
        question: "What is a struct?",
        options: ["A structure", "A composite data type containing multiple members", "A structured variable", "A structure keyword"],
        answer: 1,
        explanation: "A struct is a composite data type that groups multiple variables together.",
    },
    {
        question: "How do you access a struct member using a pointer?",
        options: ["struct arrow member", "struct period member", "asterisk struct period member", "struct period asterisk member"],
        answer: 0,
        explanation: "Use the arrow operator to access struct members through a pointer.",
    },
    {
        question: "What is typedef used for?",
        options: ["Type definition", "Creating an alias for a data type", "Type checking", "Type conversion"],
        answer: 1,
        explanation: "typedef creates an alias for an existing data type.",
    },
    {
        question: "What is the purpose of the malloc function?",
        options: ["Free memory", "Allocate memory dynamically", "Compare memory", "Copy memory"],
        answer: 1,
        explanation: "malloc allocates a specified amount of memory on the heap and returns a pointer.",
    },
    {
        question: "What is the purpose of the free function?",
        options: ["Allocate memory", "Deallocate previously allocated memory", "Free variables", "Free pointers"],
        answer: 1,
        explanation: "free deallocates memory previously allocated with malloc or calloc.",
    },
    {
        question: "What is a memory leak?",
        options: ["Leaking memory physically", "Allocated memory that is not freed", "Lost memory", "Deleted memory"],
        answer: 1,
        explanation: "A memory leak occurs when allocated memory is not deallocated, wasting memory.",
    },
    {
        question: "What is dynamic memory allocation?",
        options: ["Allocating static memory", "Memory allocation at runtime", "Allocating memory on stack", "Allocating global memory"],
        answer: 1,
        explanation: "Dynamic allocation allows memory allocation at runtime using malloc or calloc.",
    },
    {
        question: "What is the stack used for in a program?",
        options: ["Storing large data", "Local variables and function calls", "Global variables", "Dynamic memory"],
        answer: 1,
        explanation: "The stack stores local variables and maintains the call stack for functions.",
    },
    {
        question: "What is the heap used for in a program?",
        options: ["Storing function calls", "Dynamic memory allocation", "Storing constants", "Temporary storage"],
        answer: 1,
        explanation: "The heap is used for dynamic memory allocation with malloc and calloc.",
    },
    {
        question: "What is the difference between stack and heap?",
        options: ["No difference", "Stack is slow and heap is fast", "Stack is automatically managed and heap requires manual management", "Stack is larger"],
        answer: 2,
        explanation: "Stack automatically manages memory with automatic deallocation, while heap requires manual management.",
    },
    {
        question: "What does a function declaration contain?",
        options: ["Function name and parameters", "Function name, parameters, and return type", "Just function name", "Parameters and body"],
        answer: 1,
        explanation: "A function declaration specifies the return type, name, and parameter types.",
    },
    {
        question: "What is the purpose of return type in a function?",
        options: ["Name the function", "Specify what the function returns", "Define parameters", "Control flow"],
        answer: 1,
        explanation: "The return type specifies what data type the function returns.",
    },
    {
        question: "What does void return type mean?",
        options: ["Returns nothing", "Returns null", "Returns zero", "Returns undefined"],
        answer: 0,
        explanation: "void means the function returns nothing (no value returned).",
    },
    {
        question: "What is recursion?",
        options: ["Running code repeatedly", "A function calling itself", "A loop structure", "Calling multiple functions"],
        answer: 1,
        explanation: "Recursion is when a function calls itself directly or indirectly.",
    },
    {
        question: "What is a base case in recursion?",
        options: ["The first call", "The condition that stops recursion", "The recursive call", "The return value"],
        answer: 1,
        explanation: "A base case is the condition that terminates recursion to prevent infinite loops.",
    },
    {
        question: "What is an infinite loop?",
        options: ["A loop that never ends", "A loop that repeats forever", "A loop with no condition", "A broken loop"],
        answer: 1,
        explanation: "An infinite loop is a loop whose condition is always true, running forever.",
    },
    {
        question: "What is the scope of a variable?",
        options: ["Where it appears in code", "The region of code where a variable is accessible", "The size of a variable", "Its value"],
        answer: 1,
        explanation: "Scope determines where in the code a variable can be used.",
    },
    {
        question: "What is a global variable?",
        options: ["A variable used everywhere", "A variable declared outside all functions", "A variable in main", "A static variable"],
        answer: 1,
        explanation: "A global variable is declared outside all functions and accessible everywhere.",
    },
    {
        question: "What is a local variable?",
        options: ["A variable in main", "A variable declared inside a function", "A temporary variable", "A static variable"],
        answer: 1,
        explanation: "A local variable is declared inside a function and only accessible within it.",
    },
    {
        question: "What does the static keyword do?",
        options: ["Makes code faster", "Preserves variable value between function calls", "Makes variables global", "Prevents changes"],
        answer: 1,
        explanation: "static variables retain their value between function calls.",
    },
    {
        question: "What is a header file?",
        options: ["The top of a file", "A file containing function declarations and macros", "A file at the beginning", "A file with h extension"],
        answer: 1,
        explanation: "A header file contains declarations and definitions to be included in other files.",
    },
    {
        question: "What does the include directive do?",
        options: ["Includes a comment", "Includes a file in the current file", "Includes a variable", "Includes a function"],
        answer: 1,
        explanation: "The include preprocessor directive includes another file's contents.",
    },
    {
        question: "What is the difference between angle brackets and quotes in include?",
        options: ["No difference", "Angle brackets search system directories, quotes search current directory", "Quotes are faster", "Angle brackets are for variables"],
        answer: 1,
        explanation: "Angle brackets search system directories, while quotes search the current directory first.",
    },
    {
        question: "What is the purpose of a makefile?",
        options: ["Make files", "Automate compilation and linking", "Create programs", "Build executables"],
        answer: 1,
        explanation: "A makefile automates the compilation process using the make command.",
    },
    {
        question: "What is the main function?",
        options: ["A primary function", "The entry point of a C program", "The most important function", "A required function"],
        answer: 1,
        explanation: "main() is where program execution begins.",
    },
    {
        question: "What does argc represent?",
        options: ["Argument counter", "The number of command-line arguments", "Argument characters", "Argument count"],
        answer: 1,
        explanation: "argc (argument count) stores the number of command-line arguments passed to the program.",
    },
    {
        question: "What does argv represent?",
        options: ["Argument variables", "Array of command-line argument strings", "Argument values", "Argument vector"],
        answer: 1,
        explanation: "argv (argument vector) is an array of strings containing command-line arguments.",
    },
    {
        question: "What is a command-line argument?",
        options: ["Arguments to functions", "Values passed to a program when executed", "Arguments in command structure", "Program parameters"],
        answer: 1,
        explanation: "Command-line arguments are values passed to a program when it is run.",
    },
    {
        question: "What does exit with zero mean?",
        options: ["Exit with error", "Exit successfully", "Exit the program", "Stop execution"],
        answer: 1,
        explanation: "exit(0) terminates the program successfully. Non-zero indicates error.",
    },
    {
        question: "What is the purpose of a loop?",
        options: ["Circle shape", "Repeat code multiple times", "Return values", "Check conditions"],
        answer: 1,
        explanation: "Loops execute code repeatedly based on a condition.",
    },
    {
        question: "What are the main loop types in C?",
        options: ["for, while, do-while, infinite", "for, while, until", "loop, iterate, repeat", "for, foreach, while"],
        answer: 0,
        explanation: "C has for, while, and do-while loops, and infinite loops.",
    },
    {
        question: "What is the difference between while and do-while?",
        options: ["No difference", "while checks first, do-while executes at least once", "do-while is faster", "while is better"],
        answer: 1,
        explanation: "do-while executes the body at least once before checking the condition.",
    },
    {
        question: "What is the purpose of continue in a loop?",
        options: ["Continue the program", "Skip to next iteration", "Exit the loop", "Pause execution"],
        answer: 1,
        explanation: "continue skips the remaining code and goes to the next iteration.",
    },
    {
        question: "What is the purpose of break in a loop?",
        options: ["Break the code", "Exit the loop immediately", "Skip iteration", "Pause loop"],
        answer: 1,
        explanation: "break exits the loop immediately.",
    },
    {
        question: "What is a conditional statement?",
        options: ["A statement with conditions", "Code that executes based on conditions", "A loop structure", "A function call"],
        answer: 1,
        explanation: "Conditional statements execute code based on whether conditions are true or false.",
    },
    {
        question: "What is the ternary operator?",
        options: ["An operator with three parts", "condition, question mark, true value, colon, false value", "A conditional statement", "A loop operator"],
        answer: 1,
        explanation: "The ternary operator condition with question mark true value colon false value returns one of two values.",
    },
    {
        question: "What is the logical AND operator?",
        options: ["pipe pipe", "ampersand ampersand", "exclamation exclamation", "ampersand"],
        answer: 1,
        explanation: "Ampersand ampersand is the logical AND operator. Returns true if both conditions are true.",
    },
    {
        question: "What is the logical OR operator?",
        options: ["ampersand ampersand", "pipe pipe", "exclamation", "pipe"],
        answer: 1,
        explanation: "Pipe pipe is the logical OR operator. Returns true if either condition is true.",
    },
    {
        question: "What is the NOT operator?",
        options: ["ampersand ampersand", "pipe pipe", "exclamation", "tilde"],
        answer: 2,
        explanation: "The exclamation is the NOT operator. Inverts the boolean value.",
    },
    {
        question: "What does SQL stand for?",
        options: ["Standard Query Language", "Structured Query Language", "Simple Query Language", "Sequential Query Language"],
        answer: 1,
        explanation: "SQL (Structured Query Language) is used to manage and query relational databases.",
    },
    {
        question: "What is a database?",
        options: ["A base for data", "An organized collection of data", "A storage system", "A file system"],
        answer: 1,
        explanation: "A database is an organized collection of structured data stored and accessed electronically.",
    },
    {
        question: "What is a table in a database?",
        options: ["A furniture piece", "A collection of related data in rows and columns", "A data structure", "A file"],
        answer: 1,
        explanation: "A table is a set of data organized in rows and columns.",
    },
    {
        question: "What is a primary key?",
        options: ["The first key", "A unique identifier for each row", "A security key", "A special column"],
        answer: 1,
        explanation: "A primary key uniquely identifies each row in a table.",
    },
    {
        question: "What is a foreign key?",
        options: ["A non-primary key", "A key that references a primary key in another table", "An external key", "A backup key"],
        answer: 1,
        explanation: "A foreign key references a primary key in another table, establishing relationships.",
    },
    {
        question: "What is a SELECT statement used for?",
        options: ["Selecting files", "Retrieving data from a database", "Selecting data types", "Choosing a database"],
        answer: 1,
        explanation: "SELECT retrieves specific columns and rows from a database table.",
    },
    {
        question: "What does SELECT asterisk mean?",
        options: ["Select multiplication", "Select all columns", "Select everything", "Select any"],
        answer: 1,
        explanation: "SELECT asterisk retrieves all columns from a table.",
    },
    {
        question: "What does the WHERE clause do?",
        options: ["Defines location", "Filters rows based on conditions", "Specifies columns", "Orders data"],
        answer: 1,
        explanation: "WHERE filters rows to include only those matching specified conditions.",
    },
    {
        question: "What is a JOIN in SQL?",
        options: ["Joining files", "Combining data from multiple tables", "Linking databases", "Merging columns"],
        answer: 1,
        explanation: "JOIN combines rows from multiple tables based on related columns.",
    },
    {
        question: "What is an INNER JOIN?",
        options: ["A join inside a table", "Returns only matching rows from both tables", "Returns all rows", "A direct join"],
        answer: 1,
        explanation: "INNER JOIN returns only rows that have matches in both tables.",
    },
    {
        question: "What is a LEFT JOIN?",
        options: ["A join on the left", "Returns all rows from left table plus matches from right", "Returns left side only", "A partial join"],
        answer: 1,
        explanation: "LEFT JOIN returns all rows from the left table and matching rows from the right table.",
    },
    {
        question: "What is an INSERT statement used for?",
        options: ["Inserting files", "Adding new rows to a table", "Inserting columns", "Inserting values"],
        answer: 1,
        explanation: "INSERT adds new rows with data to a table.",
    },
    {
        question: "What is an UPDATE statement used for?",
        options: ["Updating programs", "Modifying existing data in a table", "Updating databases", "Changing structure"],
        answer: 1,
        explanation: "UPDATE modifies existing data in table rows.",
    },
    {
        question: "What is a DELETE statement used for?",
        options: ["Deleting files", "Removing rows from a table", "Deleting tables", "Erasing data"],
        answer: 1,
        explanation: "DELETE removes rows from a table.",
    },
    {
        question: "What does GROUP BY do?",
        options: ["Groups data alphabetically", "Groups rows sharing same column values", "Organizes tables", "Sorts data"],
        answer: 1,
        explanation: "GROUP BY aggregates rows with the same values in specified columns.",
    },
    {
        question: "What does ORDER BY do?",
        options: ["Orders files", "Sorts result set by specified columns", "Organizes tables", "Structures data"],
        answer: 1,
        explanation: "ORDER BY sorts the result set in ascending or descending order.",
    },
    {
        question: "What is an aggregate function?",
        options: ["A function that combines", "A function that performs calculations on a set of values", "A grouping function", "A sorting function"],
        answer: 1,
        explanation: "Aggregate functions (COUNT, SUM, AVG, etc.) calculate values across multiple rows.",
    },
    {
        question: "What does COUNT do?",
        options: ["Counts numbers", "Returns number of rows matching criteria", "Counts columns", "Counts values"],
        answer: 1,
        explanation: "COUNT returns the number of rows.",
    },
    {
        question: "What does SUM do?",
        options: ["Summarizes data", "Adds numeric values in a column", "Combines rows", "Totals columns"],
        answer: 1,
        explanation: "SUM calculates the total of numeric values in a column.",
    },
    {
        question: "What does AVG do?",
        options: ["Averages numbers", "Calculates mean of numeric values", "Approximates values", "Averages data"],
        answer: 1,
        explanation: "AVG calculates the average (mean) of numeric values.",
    },
    {
        question: "What is DISTINCT used for?",
        options: ["Distinguishing data", "Removing duplicate rows from results", "Finding differences", "Identifying rows"],
        answer: 1,
        explanation: "DISTINCT removes duplicate rows from query results.",
    },
    {
        question: "What is a subquery?",
        options: ["A query within a query", "A nested SELECT statement inside another SQL query", "A previous query", "A partial query"],
        answer: 1,
        explanation: "A subquery is a query nested inside another query.",
    },
    {
        question: "What is normalization in databases?",
        options: ["Making data normal", "Organizing data to reduce redundancy", "Standardizing format", "Cleaning data"],
        answer: 1,
        explanation: "Normalization reduces data redundancy and improves data integrity.",
    },
    {
        question: "What is the first normal form (1NF)?",
        options: ["First step", "Atomic values, no repeating groups", "Initial normalization", "Primary key only"],
        answer: 1,
        explanation: "1NF requires all data to be atomic (indivisible) with no repeating groups.",
    },
    {
        question: "What is a transaction in SQL?",
        options: ["A commercial deal", "A group of SQL operations treated as a single unit", "A database operation", "A query execution"],
        answer: 1,
        explanation: "A transaction groups operations ensuring all succeed or all fail together.",
    },
    {
        question: "What does COMMIT do?",
        options: ["Makes a commitment", "Saves transaction changes permanently", "Confirms operation", "Finalizes changes"],
        answer: 1,
        explanation: "COMMIT saves all changes made in the current transaction.",
    },
    {
        question: "What does ROLLBACK do?",
        options: ["Rolls back a car", "Undoes all changes in the current transaction", "Reverses operations", "Cancels changes"],
        answer: 1,
        explanation: "ROLLBACK reverts all changes made in the current transaction.",
    },
    {
        question: "What is an index in a database?",
        options: ["A number list", "A data structure that speeds up data retrieval", "A table index", "A column number"],
        answer: 1,
        explanation: "An index improves query performance by enabling faster data lookup.",
    },
    {
        question: "What is a schema?",
        options: ["A plan", "The structure defining how data is organized", "A database design", "A table layout"],
        answer: 1,
        explanation: "A schema defines the structure and organization of database objects.",
    },
    {
        question: "What is referential integrity?",
        options: ["Integrity of references", "Ensuring foreign keys reference valid primary keys", "Data consistency", "Key validation"],
        answer: 1,
        explanation: "Referential integrity ensures foreign keys always reference existing primary keys.",
    },
    {
        question: "What is Python used for?",
        options: ["Web development", "Data science, AI, automation, web development", "Only machine learning", "System administration"],
        answer: 1,
        explanation: "Python is versatile for web development, data science, AI, automation, and more.",
    },
    {
        question: "What is the syntax for a Python function?",
        options: ["function name open paren colon", "def name open paren colon", "func name open paren colon", "define name open paren colon"],
        answer: 1,
        explanation: "Python functions use def keyword followed by name and parentheses.",
    },
    {
        question: "What is indentation in Python?",
        options: ["Extra spaces", "Required whitespace defining code blocks", "Visual formatting", "Optional spacing"],
        answer: 1,
        explanation: "Indentation is mandatory in Python to define code blocks.",
    },
    {
        question: "What are the main Python data types?",
        options: ["int, float, string, boolean, list, dict, tuple", "int, float, string, boolean", "var, array, object", "number, text, bool"],
        answer: 0,
        explanation: "Python's main types include int, float, string, boolean, list, dict, and tuple.",
    },
    {
        question: "What is a list in Python?",
        options: ["A todo list", "An ordered, mutable collection of items", "A sequence of data", "An array"],
        answer: 1,
        explanation: "A list is an ordered, changeable collection enclosed in square brackets.",
    },
    {
        question: "What is a tuple in Python?",
        options: ["A two-item list", "An ordered, immutable collection", "Like a list but smaller", "A data pair"],
        answer: 1,
        explanation: "A tuple is an ordered, unchangeable collection enclosed in parentheses.",
    },
    {
        question: "What is a dictionary in Python?",
        options: ["A word reference", "An unordered collection of key-value pairs", "A list of words", "A mapping structure"],
        answer: 1,
        explanation: "A dictionary stores key-value pairs and is mutable and unordered.",
    },
    {
        question: "What is a set in Python?",
        options: ["A collection of items", "An unordered collection of unique items", "Like a list", "A single item"],
        answer: 1,
        explanation: "A set is an unordered collection of unique items enclosed in curly braces.",
    },
    {
        question: "What is list comprehension?",
        options: ["Understanding lists", "Concise syntax for creating lists from existing lists", "List complexity", "Parsing lists"],
        answer: 1,
        explanation: "List comprehension provides a concise way to create lists.",
    },
    {
        question: "What is the syntax for list comprehension?",
        options: ["[x for x in list]", "[x in list]", "[x, list]", "for x in [list]"],
        answer: 0,
        explanation: "List comprehension syntax: [expression for item in iterable].",
    },
    {
        question: "What is a lambda function?",
        options: ["A Greek letter", "An anonymous function for simple operations", "A named function", "A complex function"],
        answer: 1,
        explanation: "Lambda is an anonymous function defined with lambda keyword.",
    },
    {
        question: "What is the syntax for a lambda function?",
        options: ["lambda x: x+1", "def lambda x: x+1", "lambda open paren x close paren equals x+1", "lambda x arrow x+1"],
        answer: 0,
        explanation: "Lambda syntax: lambda arguments colon expression.",
    },
    {
        question: "What is the map function used for?",
        options: ["Creating maps", "Applying a function to all items in an iterable", "Mapping data", "Finding locations"],
        answer: 1,
        explanation: "map applies a function to every item in an iterable.",
    },
    {
        question: "What is the filter function used for?",
        options: ["Filtering emails", "Selecting items from iterable where function returns true", "Removing items", "Organizing data"],
        answer: 1,
        explanation: "filter creates new iterable with items where function returns true.",
    },
    {
        question: "What is the reduce function used for?",
        options: ["Reducing size", "Applying function cumulatively to items in iterable", "Simplifying data", "Decreasing values"],
        answer: 1,
        explanation: "reduce applies a function cumulatively to items, returning a single result.",
    },
    {
        question: "What is a decorator in Python?",
        options: ["Visual decoration", "A function that modifies another function", "Ornamental code", "A design pattern"],
        answer: 1,
        explanation: "A decorator is a function that modifies or enhances another function.",
    },
    {
        question: "What is a class in Python?",
        options: ["A classroom", "A blueprint for creating objects", "A code block", "A data structure"],
        answer: 1,
        explanation: "A class is a template for creating objects with specific attributes and methods.",
    },
    {
        question: "What is an object in Python?",
        options: ["A physical item", "An instance of a class", "A piece of code", "A variable"],
        answer: 1,
        explanation: "An object is a specific instance created from a class.",
    },
    {
        question: "What is the init method in Python?",
        options: ["Initialization flag", "Constructor method that initializes objects", "Initial value", "Setup function"],
        answer: 1,
        explanation: "The init method is the constructor method called when creating an object.",
    },
    {
        question: "What is self in Python?",
        options: ["Self reference", "Reference to the object itself", "Current object", "Instance variable"],
        answer: 1,
        explanation: "self refers to the current instance of the class.",
    },
    {
        question: "What is inheritance in Python?",
        options: ["Inheriting money", "Child class acquiring attributes from parent class", "Passing data", "Class hierarchy"],
        answer: 1,
        explanation: "Inheritance allows a child class to inherit from a parent class.",
    },
    {
        question: "What is polymorphism?",
        options: ["Many forms", "Objects of different types responding to same method", "Multiple inheritance", "Method overloading"],
        answer: 1,
        explanation: "Polymorphism allows objects of different classes to be treated similarly.",
    },
    {
        question: "What is encapsulation?",
        options: ["Putting in a capsule", "Bundling data and methods, hiding internal details", "Securing data", "Privacy"],
        answer: 1,
        explanation: "Encapsulation hides internal details and provides controlled access.",
    },
    {
        question: "What does the import statement do?",
        options: ["Import files", "Load module functionality", "Import data", "Include library"],
        answer: 1,
        explanation: "import makes functions and classes from modules available in your code.",
    },
    {
        question: "What is the difference between import and from import?",
        options: ["No difference", "import loads module, from import loads specific items", "Both are same", "import is faster"],
        answer: 1,
        explanation: "import X versus from X import Y. The latter imports specific items directly.",
    },
    {
        question: "What is exception handling in Python?",
        options: ["Handling exceptions", "Try-except blocks for error management", "Error prevention", "Error catching"],
        answer: 1,
        explanation: "Exception handling uses try-except blocks to manage errors gracefully.",
    },
    {
        question: "What is the try-except-finally structure?",
        options: ["Three exceptions", "try for code, except for errors, finally always runs", "Error management", "Exception types"],
        answer: 1,
        explanation: "try runs code, except handles errors, finally runs regardless.",
    },
    {
        question: "What is a list method append?",
        options: ["Appends paper", "Adds item to end of list", "Combines lists", "Sorts list"],
        answer: 1,
        explanation: "append adds a single item to the end of a list.",
    },
    {
        question: "What is the range function used for?",
        options: ["Defining ranges", "Creating sequence of numbers", "Finding range", "Setting bounds"],
        answer: 1,
        explanation: "range generates a sequence of numbers for iteration.",
    },
    {
        question: "What is enumerate used for?",
        options: ["Listing items", "Getting index and value while iterating", "Counting items", "Numbering items"],
        answer: 1,
        explanation: "enumerate provides both index and value while iterating.",
    },
    {
        question: "What is the zip function used for?",
        options: ["Zipping files", "Combining multiple iterables element-wise", "Organizing data", "Grouping items"],
        answer: 1,
        explanation: "zip combines multiple iterables into tuples of corresponding elements.",
    },
    {
        question: "What does HTML stand for?",
        options: ["Hypertext Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"],
        answer: 0,
        explanation: "HTML (Hypertext Markup Language) is used to structure web page content.",
    },
    {
        question: "What is the purpose of HTML?",
        options: ["Styling pages", "Creating structure and content of web pages", "Adding interactivity", "Managing databases"],
        answer: 1,
        explanation: "HTML provides the structure and semantic meaning of web content.",
    },
    {
        question: "What does CSS stand for?",
        options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Code Style Sheets"],
        answer: 1,
        explanation: "CSS (Cascading Style Sheets) styles the appearance of HTML elements.",
    },
    {
        question: "What is the purpose of CSS?",
        options: ["Structure content", "Style and layout web pages", "Add functionality", "Create databases"],
        answer: 1,
        explanation: "CSS controls visual presentation and layout of HTML elements.",
    },
    {
        question: "What does JavaScript do?",
        options: ["Manages databases", "Adds interactivity and behavior to web pages", "Styles pages", "Structures content"],
        answer: 1,
        explanation: "JavaScript enables client-side interactivity and dynamic behavior.",
    },
    {
        question: "What is the DOM?",
        options: ["Database Object Model", "Document Object Model", "Domain Object Manager", "Data Organization Model"],
        answer: 1,
        explanation: "The DOM is a tree representation of HTML elements that JavaScript can manipulate.",
    },
    {
        question: "What is event handling in JavaScript?",
        options: ["Handling errors", "Responding to user actions like clicks", "Managing events", "Event creation"],
        answer: 1,
        explanation: "Event handling executes code in response to user interactions.",
    },
    {
        question: "What is a callback function?",
        options: ["A returned function", "A function passed to another function to execute later", "A previous function", "A recursive function"],
        answer: 1,
        explanation: "A callback is a function passed as an argument to execute later.",
    },
    {
        question: "What is a promise in JavaScript?",
        options: ["A verbal agreement", "An object representing eventual completion or failure", "A guarantee", "An async value"],
        answer: 1,
        explanation: "A promise represents the eventual result of an async operation.",
    },
    {
        question: "What is async/await?",
        options: ["Waiting for someone", "Syntax for handling asynchronous operations cleaner", "Asynchronous waiting", "Delayed execution"],
        answer: 1,
        explanation: "async/await simplifies promise-based asynchronous code.",
    },
    {
        question: "What is a CSS selector?",
        options: ["Selecting CSS", "Pattern for targeting HTML elements", "Choosing styles", "Element selection"],
        answer: 1,
        explanation: "CSS selectors target HTML elements to apply styles.",
    },
    {
        question: "What is the difference between class and ID selectors?",
        options: ["No difference", "ID is unique per page, class can be reused", "Class is unique", "ID is repeatable"],
        answer: 1,
        explanation: "ID selectors target one unique element, class selectors target multiple.",
    },
    {
        question: "What is the CSS box model?",
        options: ["A box shape", "Content, padding, border, and margin of elements", "Element structure", "Layout system"],
        answer: 1,
        explanation: "The box model consists of content, padding, border, and margin.",
    },
    {
        question: "What is flexbox used for?",
        options: ["Flexible boxes", "Flexible layout system for arranging elements", "Flexible content", "Flex properties"],
        answer: 1,
        explanation: "Flexbox provides flexible one-dimensional layout capabilities.",
    },
    {
        question: "What is CSS grid?",
        options: ["Grid lines", "Two-dimensional layout system for complex designs", "Grid structure", "Grid template"],
        answer: 1,
        explanation: "CSS Grid is a powerful two-dimensional layout system.",
    },
    {
        question: "What is responsive design?",
        options: ["Designs that respond", "Adapting design to different screen sizes", "Interactive design", "Dynamic layout"],
        answer: 1,
        explanation: "Responsive design ensures websites work well on all devices.",
    },
    {
        question: "What is a media query?",
        options: ["Querying media", "CSS rule applied based on device characteristics", "Media selection", "Responsive rule"],
        answer: 1,
        explanation: "Media queries apply styles based on screen size or device type.",
    },
    {
        question: "What is a framework in web development?",
        options: ["Framework structure", "Pre-built collection of tools and libraries", "Code framework", "Template system"],
        answer: 1,
        explanation: "A framework provides pre-built components and structure for development.",
    },
    {
        question: "What is React?",
        options: ["A chemical reaction", "A JavaScript library for building UIs", "A framework", "A development tool"],
        answer: 1,
        explanation: "React is a library for creating interactive user interfaces with components.",
    },
    {
        question: "What are components in React?",
        options: ["Computer parts", "Reusable pieces of UI", "JavaScript functions", "Element parts"],
        answer: 1,
        explanation: "Components are reusable UI pieces that can be combined to build interfaces.",
    },
    {
        question: "What is the Virtual DOM in React?",
        options: ["A fake DOM", "In-memory representation for optimizing updates", "JavaScript copy", "Cache system"],
        answer: 1,
        explanation: "The Virtual DOM is an in-memory representation enabling efficient updates.",
    },
    {
        question: "What is state in React?",
        options: ["Status information", "Data that changes and triggers re-renders", "Component data", "Variable state"],
        answer: 1,
        explanation: "State is component data that can change and causes UI updates.",
    },
    {
        question: "What are props in React?",
        options: ["Properties", "Arguments passed to components", "Component data", "Configurations"],
        answer: 1,
        explanation: "Props are arguments passed to React components for customization.",
    },
    {
        question: "What is the difference between state and props?",
        options: ["No difference", "State is mutable and internal, props are immutable and external", "Props are mutable", "State is external"],
        answer: 1,
        explanation: "State is mutable and internal, props are immutable and passed from parent.",
    },
    {
        question: "What is HTTP?",
        options: ["Hypertext Transfer Protocol", "High Tech Transfer Protocol", "Home Transmission Protocol", "Hypertext Text Protocol"],
        answer: 0,
        explanation: "HTTP is the protocol for transferring data over the web.",
    },
    {
        question: "What are HTTP methods?",
        options: ["Browser methods", "GET, POST, PUT, DELETE for different operations", "Request types", "Web methods"],
        answer: 1,
        explanation: "HTTP methods define operations: GET retrieves, POST creates, PUT updates, DELETE removes.",
    },
    {
        question: "What is REST?",
        options: ["Taking a break", "Representational State Transfer architectural style", "REST API design", "Web design pattern"],
        answer: 1,
        explanation: "REST is an architectural style for building web services using HTTP methods.",
    },
    {
        question: "What is a REST API?",
        options: ["API at rest", "API following REST principles for web service", "API design", "Network API"],
        answer: 1,
        explanation: "A REST API exposes endpoints that follow REST principles for data access.",
    },
    {
        question: "What is JSON?",
        options: ["Java Script Object Network", "JavaScript Object Notation", "Data format", "Web format"],
        answer: 1,
        explanation: "JSON is a lightweight data format for exchanging data.",
    },
    {
        question: "What is the purpose of a web server?",
        options: ["Serve food", "Deliver web content to browsers", "Store websites", "Manage networks"],
        answer: 1,
        explanation: "A web server stores and delivers web pages to clients.",
    },
    {
        question: "What is a database management system?",
        options: ["A tool for organizing files", "Software for managing data in databases", "A data storage device", "A backup system"],
        answer: 1,
        explanation: "A DBMS is software that manages creation, access, and control of database files."
    },
    {
        question: "What is SQL used for?",
        options: ["Managing databases", "Creating web pages", "Writing documents", "Sending emails"],
        answer: 0,
        explanation: "SQL is used to manage and query relational databases."
    },
    {
        question: "What is a database index?",
        options: ["A list of records", "A structure that improves query performance", "A backup copy", "A sorting mechanism"],
        answer: 1,
        explanation: "An index is a data structure that speeds up database query operations."
    },
    {
        question: "What does ACID stand for in databases?",
        options: ["Automated Computer Input Data", "Atomicity, Consistency, Isolation, Durability", "Access Control Identity Database", "Automated Catalog Index Design"],
        answer: 1,
        explanation: "ACID properties ensure reliable database transactions."
    },
    {
        question: "What is a view in a database?",
        options: ["A visual display", "A virtual table based on a query result", "A database backup", "A data snapshot"],
        answer: 1,
        explanation: "A view is a virtual table created from a query on one or more tables."
    },
    {
        question: "What is a stored procedure?",
        options: ["A stored document", "A set of SQL statements stored in the database", "A backup procedure", "An archival method"],
        answer: 1,
        explanation: "A stored procedure is a precompiled set of SQL statements stored in the database."
    },
    {
        question: "What is a trigger in databases?",
        options: ["A warning system", "An automatic action executed in response to certain events", "A safety mechanism", "A backup trigger"],
        answer: 1,
        explanation: "A trigger automatically executes when specified database events occur."
    },
    {
        question: "What is data redundancy?",
        options: ["Excess data", "Duplication of data in multiple locations", "Data corruption", "Data loss"],
        answer: 1,
        explanation: "Data redundancy is the duplication of data which can lead to inconsistencies."
    },
    {
        question: "What is a relational database?",
        options: ["A database with relationships", "A database organizing data in tables with relationships", "A connected database", "A networked database"],
        answer: 1,
        explanation: "A relational database organizes data in tables with defined relationships."
    },
    {
        question: "What is NoSQL?",
        options: ["Not SQL", "Non-relational database technology", "No Structured Query Language", "Network Operating System Query Language"],
        answer: 1,
        explanation: "NoSQL refers to non-relational database systems that store data differently than traditional tables."
    },
    {
        question: "What is MongoDB?",
        options: ["Money storage system", "A NoSQL document-oriented database", "A data management tool", "A backup system"],
        answer: 1,
        explanation: "MongoDB is a popular NoSQL document-oriented database."
    },
    {
        question: "What is object-oriented programming?",
        options: ["Programming with objects", "Programming paradigm based on objects and classes", "Program organization", "Object storage"],
        answer: 1,
        explanation: "OOP is a programming paradigm based on organizing code into objects and classes."
    },
    {
        question: "What is a method in object-oriented programming?",
        options: ["A procedure", "A function associated with an object or class", "A technique", "A plan"],
        answer: 1,
        explanation: "A method is a function or procedure associated with an object or class."
    },
    {
        question: "What is an interface in programming?",
        options: ["A visual display", "A contract defining methods that classes must implement", "A user interface", "A boundary layer"],
        answer: 1,
        explanation: "An interface specifies a contract that implementing classes must follow."
    },
    {
        question: "What is an abstract class?",
        options: ["A theoretical class", "A class that cannot be instantiated directly", "A complex class", "A base class"],
        answer: 1,
        explanation: "An abstract class cannot be instantiated and is meant to be inherited from."
    },
    {
        question: "What is a constructor?",
        options: ["A building worker", "A special method that initializes an object", "A class builder", "An initialization function"],
        answer: 1,
        explanation: "A constructor is a special method that runs when an object is created."
    },
    {
        question: "What is a destructor?",
        options: ["A wrecking device", "A special method that cleans up when an object is destroyed", "An object remover", "A cleanup function"],
        answer: 1,
        explanation: "A destructor is called when an object is destroyed to free resources."
    },
    {
        question: "What is method overloading?",
        options: ["Too many methods", "Multiple methods with same name but different parameters", "Method reuse", "Function duplication"],
        answer: 1,
        explanation: "Method overloading allows multiple methods with the same name but different parameters."
    },
    {
        question: "What is method overriding?",
        options: ["Preventing methods", "Redefining a method in a child class", "Method replacement", "Function modification"],
        answer: 1,
        explanation: "Method overriding allows a child class to redefine a parent class method."
    },
    {
        question: "What is a software design pattern?",
        options: ["A code pattern", "A reusable solution to a common programming problem", "A coding style", "A program structure"],
        answer: 1,
        explanation: "A design pattern is a proven reusable solution to common programming problems."
    },
    {
        question: "What is the Model-View-Controller (MVC) pattern?",
        options: ["A programming language", "An architectural pattern separating concerns into Model, View, and Controller", "A design framework", "A web structure"],
        answer: 1,
        explanation: "MVC separates applications into Model, View, and Controller components."
    },
    {
        question: "What is the singleton pattern?",
        options: ["A single item", "A pattern ensuring only one instance of a class exists", "A unique class", "A single object"],
        answer: 1,
        explanation: "The singleton pattern restricts a class to have only one instance."
    },
    {
        question: "What is the observer pattern?",
        options: ["A watching pattern", "A pattern where objects notify observers of state changes", "An observation system", "A monitoring pattern"],
        answer: 1,
        explanation: "The observer pattern enables objects to notify multiple observers of state changes."
    },
    {
        question: "What is version control?",
        options: ["Software versioning", "A system for tracking and managing changes to code", "Version management", "Code control"],
        answer: 1,
        explanation: "Version control tracks and manages changes to source code over time."
    },
    {
        question: "What is Git?",
        options: ["Get in programming", "A distributed version control system", "A code repository", "A data system"],
        answer: 1,
        explanation: "Git is a widely used distributed version control system for managing code."
    },
    {
        question: "What is a repository in Git?",
        options: ["A storage place", "A directory containing project files and version history", "A backup location", "A data store"],
        answer: 1,
        explanation: "A Git repository is a directory that contains project files and complete version history."
    },
    {
        question: "What is a commit in version control?",
        options: ["A promise", "A snapshot of changes saved to the repository", "A change record", "A save point"],
        answer: 1,
        explanation: "A commit saves a snapshot of changes to the repository with a descriptive message."
    },
    {
        question: "What is a branch in Git?",
        options: ["A tree branch", "An independent line of development", "A code path", "A separate version"],
        answer: 1,
        explanation: "A branch allows parallel development without affecting the main code."
    },
    {
        question: "What is merging in version control?",
        options: ["Combining files", "Integrating changes from one branch into another", "Joining code", "Combining versions"],
        answer: 1,
        explanation: "Merging integrates changes from different branches into a single branch."
    },
    {
        question: "What is a merge conflict?",
        options: ["A disagreement", "A situation where Git cannot automatically merge changes", "An error state", "A conflict resolution"],
        answer: 1,
        explanation: "A merge conflict occurs when changes in different branches cannot be automatically merged."
    },
    {
        question: "What is continuous integration?",
        options: ["Continuous improvement", "Regularly integrating code changes and running automated tests", "Constant programming", "Continuous development"],
        answer: 1,
        explanation: "Continuous integration automatically integrates and tests code changes frequently."
    },
    {
        question: "What is continuous deployment?",
        options: ["Continuous development", "Automatically deploying code changes to production", "Constant releases", "Regular updates"],
        answer: 1,
        explanation: "Continuous deployment automatically releases tested code changes to production."
    },
    {
        question: "What is a unit test?",
        options: ["A single test", "A test that verifies a single unit of code", "A comprehensive test", "A system test"],
        answer: 1,
        explanation: "A unit test verifies that a single function or component works correctly."
    },
    {
        question: "What is test coverage?",
        options: ["Test documentation", "The percentage of code executed by tests", "Test completeness", "Test quantity"],
        answer: 1,
        explanation: "Test coverage measures the percentage of code that is tested."
    },
    {
        question: "What is debugging?",
        options: ["Removing insects", "Finding and fixing errors in code", "Code improvement", "Problem solving"],
        answer: 1,
        explanation: "Debugging is the process of finding and removing errors from code."
    },
    {
        question: "What is a debugger?",
        options: ["A tool for insects", "A software tool for stepping through code and finding errors", "An error detector", "A code analyzer"],
        answer: 1,
        explanation: "A debugger is a tool that allows stepping through code and inspecting variables."
    },
    {
        question: "What is a breakpoint in debugging?",
        options: ["A pause point", "A point where execution pauses for inspection", "An error location", "A program stop"],
        answer: 1,
        explanation: "A breakpoint pauses program execution at a specific location for inspection."
    },
    {
        question: "What is API documentation?",
        options: ["Code documentation", "Documentation describing how to use an API", "Technical documentation", "Software manual"],
        answer: 1,
        explanation: "API documentation explains the functions, parameters, and usage of an API."
    },
    {
        question: "What is a code review?",
        options: ["Reviewing code structure", "Process of examining code for quality and correctness", "Code inspection", "Quality check"],
        answer: 1,
        explanation: "Code review is the practice of examining code for errors and improvements."
    },
    {
        question: "What is refactoring?",
        options: ["Rebuilding code", "Restructuring code without changing functionality", "Code improvement", "Code rewriting"],
        answer: 1,
        explanation: "Refactoring improves code structure without altering its external behavior."
    },
    {
        question: "What is technical debt?",
        options: ["Financial debt", "Code that needs improvement or fixes", "Development cost", "Programming problem"],
        answer: 1,
        explanation: "Technical debt refers to suboptimal code that will require future fixes."
    },
    {
        question: "What is agile development?",
        options: ["Quick development", "Software development methodology emphasizing flexibility and iteration", "Fast programming", "Rapid development"],
        answer: 1,
        explanation: "Agile development uses iterative and incremental approaches with frequent feedback."
    },
    {
        question: "What is a sprint in agile development?",
        options: ["A fast run", "A fixed time period for completing a set of tasks", "A quick project", "An iteration cycle"],
        answer: 1,
        explanation: "A sprint is a short time period (usually 1-4 weeks) for completing planned work."
    }
];
